import { z } from 'zod'
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { jsonResult, errorResult, type ToolContext } from '../helpers'
import { findSimilarExamples } from '../../services/retrieval'
import { assertSequenceOwned } from './sequences'

const EXAMPLE_COLUMNS = 'id, context, subject, body, outcome, tags, sequence_id, step_number, created_at'

export function registerExampleTools(server: McpServer, ctx: ToolContext): void {
  const { supabase, env, userId } = ctx

  server.registerTool(
    'list_examples',
    {
      title: 'List outreach examples',
      description:
        'List the user\'s saved outreach examples (successful emails used as AI reference material), newest first.',
      inputSchema: {
        tag: z.string().optional().describe('Only examples tagged with this tag'),
        outcome: z.string().optional().describe('Only examples with this outcome (e.g. "replied", "meeting_booked")'),
        sequence_id: z.string().optional().describe('Only steps of this sequence (UUID), ordered by step'),
        limit: z.number().int().min(1).max(100).optional().describe('Max results (default all)'),
      },
      annotations: { readOnlyHint: true },
    },
    async ({ tag, outcome, sequence_id, limit }) => {
      let query = supabase
        .from('outreach_examples')
        .select(EXAMPLE_COLUMNS)
        .eq('user_id', userId)

      query = sequence_id
        ? query.eq('sequence_id', sequence_id).order('step_number', { ascending: true })
        : query.order('created_at', { ascending: false })

      if (tag) query = query.contains('tags', [tag])
      if (outcome) query = query.eq('outcome', outcome)
      if (limit) query = query.limit(limit)

      const { data, error } = await query
      if (error) return errorResult(error.message)
      return jsonResult({ examples: data })
    }
  )

  server.registerTool(
    'search_examples',
    {
      title: 'Search outreach examples',
      description:
        'Semantic search over the user\'s outreach examples using embeddings. Describe the situation (e.g. "cold outreach to a K-12 facilities director about energy costs") and get the most similar past emails with similarity scores.',
      inputSchema: {
        query: z.string().min(1).describe('Natural-language description of the outreach situation'),
        limit: z.number().int().min(1).max(20).optional().describe('Max results (default 5)'),
      },
      annotations: { readOnlyHint: true },
    },
    async ({ query, limit }) => {
      const examples = await findSimilarExamples(
        supabase,
        env.OPENAI_API_KEY,
        userId,
        query,
        limit ?? 5
      )
      return jsonResult({ examples })
    }
  )

  server.registerTool(
    'create_example',
    {
      title: 'Create outreach example',
      description:
        'Save an outreach example (an email that worked well) for the AI to reference when drafting. An embedding is generated asynchronously so the example becomes semantically searchable shortly after creation.',
      inputSchema: {
        context: z
          .string()
          .min(1)
          .describe('The situation this email was written for (who, why, what stage)'),
        subject: z.string().optional().describe('Email subject line'),
        body: z.string().min(1).describe('The email body that was sent'),
        outcome: z.string().optional().describe('What happened (e.g. "replied", "meeting_booked")'),
        tags: z.array(z.string()).optional().describe('Tags for filtering'),
        sequence_id: z
          .string()
          .optional()
          .describe('Sequence (UUID) this example is a step of; requires step_number'),
        step_number: z
          .number()
          .int()
          .min(1)
          .optional()
          .describe('1-based position within the sequence; requires sequence_id'),
      },
      annotations: { destructiveHint: false },
    },
    async ({ context, subject, body, outcome, tags, sequence_id, step_number }) => {
      if ((sequence_id === undefined) !== (step_number === undefined)) {
        return errorResult('sequence_id and step_number must be provided together')
      }
      if (sequence_id) {
        const ownership = await assertSequenceOwned(ctx, sequence_id)
        if (ownership) return errorResult(ownership)
      }

      const { data, error } = await supabase
        .from('outreach_examples')
        .insert({ user_id: userId, context, subject, body, outcome, tags, sequence_id, step_number })
        .select(EXAMPLE_COLUMNS)
        .single()

      if (error) return errorResult(error.message)

      // Embedding is generated by the queue consumer (jobs/embed-example.ts).
      if (data) {
        await env.EMBED_EXAMPLE_QUEUE.send({ exampleId: data.id })
      }

      return jsonResult({ example: data })
    }
  )

  server.registerTool(
    'update_example',
    {
      title: 'Update outreach example',
      description:
        'Update fields of an existing outreach example. Changing context, subject, or body triggers re-embedding. Set sequence_id + step_number to place it in a sequence, sequence_id null to remove it, or step_number alone to move it within its current sequence.',
      inputSchema: {
        id: z.string().describe('Example id (UUID)'),
        context: z.string().min(1).optional(),
        subject: z.string().optional(),
        body: z.string().min(1).optional(),
        outcome: z.string().optional(),
        tags: z.array(z.string()).optional(),
        sequence_id: z
          .string()
          .nullable()
          .optional()
          .describe('Sequence (UUID) to place this example in (requires step_number), or null to remove it from its sequence'),
        step_number: z.number().int().min(1).optional().describe('1-based position within the sequence'),
      },
      annotations: { destructiveHint: false, idempotentHint: true },
    },
    async ({ id, sequence_id, step_number, ...fields }) => {
      const updates: Record<string, unknown> = {}
      for (const [key, value] of Object.entries(fields)) {
        if (value !== undefined) updates[key] = value
      }

      if (sequence_id === null) {
        updates.sequence_id = null
        updates.step_number = null
      } else if (sequence_id !== undefined) {
        if (step_number === undefined) {
          return errorResult('step_number is required when setting sequence_id')
        }
        const ownership = await assertSequenceOwned(ctx, sequence_id)
        if (ownership) return errorResult(ownership)
        updates.sequence_id = sequence_id
        updates.step_number = step_number
      } else if (step_number !== undefined) {
        updates.step_number = step_number
      }

      if (Object.keys(updates).length === 0) return errorResult('No fields to update')

      const { data, error } = await supabase
        .from('outreach_examples')
        .update(updates)
        .eq('id', id)
        .eq('user_id', userId)
        .select(EXAMPLE_COLUMNS)
        .single()

      if (error || !data) return errorResult(error?.message ?? 'Example not found')

      // Re-embed if searchable content changed.
      if (updates.context !== undefined || updates.body !== undefined || updates.subject !== undefined) {
        await env.EMBED_EXAMPLE_QUEUE.send({ exampleId: data.id })
      }

      return jsonResult({ example: data })
    }
  )

  server.registerTool(
    'delete_example',
    {
      title: 'Delete outreach example',
      description: 'Permanently delete an outreach example.',
      inputSchema: {
        id: z.string().describe('Example id (UUID)'),
      },
      annotations: { destructiveHint: true },
    },
    async ({ id }) => {
      const { data, error } = await supabase
        .from('outreach_examples')
        .delete()
        .eq('id', id)
        .eq('user_id', userId)
        .select('id')

      if (error) return errorResult(error.message)
      if (!data?.length) return errorResult('Example not found')
      return jsonResult({ deleted: true, id })
    }
  )
}
